2tons/front-end

package-lock.json, package.json, src/App.js, src/components/Header.js, src/locales/fr/translation.js, src/pages/Coaches/components/CoachTable.js, src/pages/Workshops/components/WorkshopModal.js, src/pages/Workshops/components/WorkshopModalForm.js, src/pages/Workshops/components/WorkshopTable.js, src/pages/Workshops/index.js
- Table des workshop
- Fake data dans le component (je n'ai pas utilise de mock pour le moment)
- Changement de style de la navbar
- Ajout d'une seconde navbar pour voir si c'est pertinent
=> Workshop Table

.eslintrc.json, .vscode/settings.json, package-lock.json, src/pages/Simulation/components/ActionCardItem.js, src/pages/Simulation/components/ActionCardsEntry.js, src/pages/Simulation/components/ActionCardsForm.js, src/pages/Simulation/components/NewRoundModalForm.js, src/pages/Simulation/components/ParticipantsTable.js, src/selectors/workshopSelector.js
Authorize next round action with batches from previous rounds
Fix eslint errors
=> Round management

src/App.js, src/actions/errors.js, src/actions/workshops.js, src/components/CommonModal.js, src/components/Navbar.js, src/locales/fr/translation.js, src/pages/Workshops/components/WorkshopModalForm.js, src/pages/Workshops/components/WorkshopTable.js, src/pages/Workshops/index.js, src/reducers/errors.js, src/reducers/index.js, src/selectors/workshopSelector.js, src/utils/api/handleFetch.js
- Add 2 new actions: ERROR and RESET_ERROR_MESSAGE
- Add errors reducer to centralize errors
- Add an bootstrap Alert component at the bottom of the Navbar
- Modify Workshop errors management
=> Add generic alert mechanism

src/reducers/utils/model.js, src/reducers/utils/model.spec.js, src/reducers/workshop.js
- Résolution de problèmes liés au calcul du score Social : 
- Le nombre de participants n'est plus hardcodé
- Correction d'un problème de variables mal nomées
- Ajout des tests
=> fix socialScore computation

src/reducers/utils/bufferCarbonVariables.js, src/reducers/utils/bufferCarbonVariables.spec.js, src/reducers/utils/surveyVariablesSchema.js
Remove coachCommute as it was a duplicate of urbanBus
=> Minor changes on the model

src/pages/Participants/components/NewParticipantItem.js, src/pages/Participants/index.js
Fixes #94 ; small bootstrap layout modifs to participant screen.
=> Disable participant screen after start

src/pages/Simulation/components/NewRoundModalForm.js
=> It's now possible to select year - 1

src/components/Navbar.js
=> Fix Navbar vertical size

src/components/AddNewButton.js, src/pages/Participants/index.js
Disable "Add new participant" button, forgotten in the previous PR #98
=> Disable participant screen after workshop start - small fix

src/pages/Workshops/components/WorkshopModalForm.js, src/pages/Workshops/components/WorkshopTable.js, src/pages/Workshops/index.js
Resolves #56.
There is no proper date input form (e.g. a pop-up calendar) and validation is basic - using `moment.isValid()`but it should be sufficient for now.
=> Add date to modal, fix date displayed in the table

src/pages/Simulation/components/EvolutionCarbon.js
- Trajectory line for objective #69 
- Colors for average participants, average population, objective will be the same across all simulations (not the case now)
=> Evolution graph minor updates

src/actions/workshop.js, src/actions/workshop.spec.js, src/reducers/workshop.js
Add unit tests for initRound and startRound actions
=> Add unit tests for initRound and startRound actions

src/reducers/utils/model.js, src/reducers/utils/model.spec.js, src/reducers/workshop.js
- Fix actions taken by citizens
- Add memory for collectiveBudget fixes #112 
closes #112 #103 #71
=> Citizen actions and collective budget

src/reducers/utils/model.js, src/reducers/utils/model.spec.js
- Fix issue with actions taken by citizens
=> hotfix actions taken by citizens

.eslintrc.json, src/actions/workshop.js, src/reducers/utils/model.js, src/reducers/utils/model.spec.js, src/reducers/workshop.js, src/reducers/workshop.spec.js
- Fix: apply global actions on citizens
- Fix: add ratioCitizens in social scores
- Fix: when 2 simultaneous action change the same carbonVariable, both are applied #116 
closes #116
=> Fixes model 4

package-lock.json, package.json, src/reducers/utils/model.js, src/reducers/utils/model.spec.js, src/reducers/workshop.js
- fix: Collective budget is actualised even during individual rounds
=> Fixes model : Collective budget

src/pages/Participants/components/NewParticipantItem.js, src/pages/Participants/components/ParticipantStatusAction.js, src/pages/Participants/index.js
Handle navigation from participants page to data page
=> Handle navigation from participants page to data page

src/pages/Data/components/DataEditor.js, src/pages/Data/components/SurveyVariablesDataSheet.js, src/selectors/surveyVariablesSelector.js, src/selectors/surveyVariablesSelector.spec.js
Allow only numeric keys [0-9] plus . and , for numeric values
=> Add DataEditor for numbers

src/reducers/utils/bufferCarbonVariables.spec.js, src/reducers/workshop.js
- use correct round actions to decreaes collective budget
fixes #149
=> Fixes model 7

src/actions/participants.js, src/pages/Participants/components/NewParticipantItem.js, src/pages/Participants/components/ParticipantItemForm.js, src/pages/Participants/index.js, src/reducers/workshop.js, src/utils/api/index.js
=> Button 'Envoi formulaire' is now working. Status is updated

src/pages/Simulation/components/FootprintGraph.js, src/pages/Simulation/index.js
=> Fix missing legend in participant footprint graph

src/actions/workshop.js, src/pages/Simulation/components/EvolutionCarbon.js, src/pages/Simulation/components/FootprintGraph.js, src/reducers/workshop.js, src/selectors/footprintSelector.spec.js, src/selectors/footprintSelectors.js
- Refactor selectors
- Add START_WORKSHOP & WORKSHOP_STARTED actions to wait end of compute footprints when starting a simulation (participants info where missing in graph the first time)
=> Refactor selectors. Add START_WORKSHOP & WORKSHOP_STARTED actions
